zeus-tp:
  api:
    version: 1.0.0
server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/tpdb?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: tpapp
    password: password
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  flyway:
    user: tpadmin
    password: password
  profiles:
    active: local, clean
logging:
  file:
    name: logs/local/tp.log
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace
