openapi: 3.0.1
info:
  title: OpenAPI definition
  version: v0
servers:
- url: http://localhost:8081
  description: Generated server url
paths:
  /api/v1/tp:
    get:
      tags:
      - trading-partner
      description: Get All the trading partner in the system
      operationId: getAllTradingPartners
      responses:
        "200":
          description: Successfully retrieved all the trading partners
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TradingPartnerRequest'
components:
  schemas:
    TradingPartnerRequest:
      type: object
      properties:
        tradingPartnerRequest:
          type: string
